### ISSUE TITLE
Possible changes when Cities: Skylines - Snowfall comes out.

### ISSUE THREAD

**Issue by bloodypenguin** [justacid/Skylines-ExtendedPublicTransport#11]
Hello Tobias! Will you be able to accept a pull request and publish an update (if it's needed) when Snowfall comes out? See trailer [here](https://www.youtube.com/watch?v=D16RJNPRFxQ)

**Comment by justacid** [comment]
Hopefully so (I don't know if I would be able to address issues in a timely manner) - but I'd also be interested in handing over the project if somebody willing to maintain EPTUI could be found

**Comment by bloodypenguin** [comment]
I want to maintain the mod, but it won't be possible to hand the mod over to me without duplicating it in workshop. The best thing I can do is to send my updated dlls for you to upload.

**Comment by justacid** [comment]
It's possible to add contributors in the steam workshop, does that not allow one to update dlls?

**Comment by bloodypenguin** [comment]
Looks like it doesn't.

**Comment by justacid** [comment]
Hmm that's unfortunate... well we could still try, worst case I'd just give you access to everything and update the dll myself

**Comment by justacid** [comment]
Well, I guess with the newest update and the mod functionality making it in the base game, the issue is resolved. :)
